version: '3.4'

services:
  signedgeservice:
    image: ${DOCKER_REGISTRY-}signedgeservice
    stdin_open: true
    tty: true
    build:
      context: .
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      dockerfile: SignEdgeService/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=http://+:80
        - KnownProxy=127.0.0.1
    ports:
        - "127.0.0.1:80:80"
    volumes:
        - certificate:/etc/certificate/
    networks:
        certificate_network:
            ipv4_address: 128.0.0.2
volumes:
  certificate:
networks:
  certificate_network:
    external: false
    name: certificate_network
    ipam:
      config:
        - subnet: 128.0.0.0/8