version: '3.4'

services:
  signedgeservice:
    image: happyhakunamatata/littlemozzarellanetwork:signedgeservice
    stdin_open: true
    tty: true
    build:
      context: .
      platforms:
        - "linux/amd64"
        - "linux/arm64"
      dockerfile: SignEdgeService/Dockerfile
    environment:
        - ASPNETCORE_ENVIRONMENT=Production
        - ASPNETCORE_URLS=http://+:8080
        - KnownProxy=128.0.0.3
    ports:
        - "127.0.0.1:8080:8080"
    volumes:
        - certificate:/etc/certificate/
    networks:
        certificate_network:
            ipv4_address: 128.0.0.2
volumes:
  certificate:
    name: certificate
networks:
  certificate_network:
    external: false
    name: certificate_network
    ipam:
      config:
        - subnet: 128.0.0.0/8